version: "3.7"
networks:
  default:
    name: notes-app-network
    external: true
services:
  gateway: 
    image: "notes-app-gateway"
    ports:
      - 3000:80
  zookeeper:
    image: "bitnami/zookeeper:latest"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
  users:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./users/:/app
    environment:
      PG_HOST: "auth-db"
      PG_USER: "auth-api"
      PG_PASSWORD: "secret4authapi"
      PG_DB: "users"
    depends_on:
      - auth-db
  users1:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./users/:/app
    environment:
      PG_HOST: "auth-db"
      PG_USER: "auth-api"
      PG_PASSWORD: "secret4authapi"
      PG_DB: "users"
    depends_on:
      - auth-db
  notes:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./notes/:/app
    environment:
      PG_HOST: "notes-db"
      PG_USER: "notes-api"
      PG_PASSWORD: "secret4notesapi"
      PG_DB: "notes"
    depends_on:
      - notes-db
  auth-db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "auth-api"
      POSTGRES_PASSWORD: "secret4authapi"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./auth-db:/var/lib/postgresql/data
  notes-db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "notes-api"
      POSTGRES_PASSWORD: "secret4notesapi"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./notes-db:/var/lib/postgresql/data
